
package oracle.demo.oow.bd.loader.analytics;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;

import java.io.IOException;

import java.sql.SQLException;

import java.util.Hashtable;

import oracle.demo.oow.bd.constant.Constant;
import oracle.demo.oow.bd.dao.CastDAO;
import oracle.demo.oow.bd.dao.CrewDAO;
import oracle.demo.oow.bd.dao.MovieDAO;
import oracle.demo.oow.bd.loader.CustomerProfileLoader;
import oracle.demo.oow.bd.pojo.SearchCriteria;
import oracle.demo.oow.bd.to.CastTO;
import oracle.demo.oow.bd.to.CrewTO;
import oracle.demo.oow.bd.to.MovieTO;
import oracle.demo.oow.bd.util.KeyUtil;
import oracle.demo.oow.bd.util.StringUtil;

/**
 * This class is used to refresh the recommendations for a specific customer.
 * It uses the recommendations that were generated by Oracle Advanced Analytics
 * in Oracle Database.
 */

public class MovieRecommendationRefresh {

    public MovieRecommendationRefresh() {
        super();
    }

    /**
     *Refreshes the recommendations for a customer.
     * @param args The customer id that will be refreshed.
     */
    public static void main(String[] args) {
        MovieRecommendationRefresh mu = new MovieRecommendationRefresh();
        
        if (args.length != 1) {
            System.out.println("A single customer id is required in order to refresh recommendations.");
            System.exit(0);
        }

        // UserItemLoader loads recommendations from a file or from the database.                        
        UserItemLoader uit = new UserItemLoader();

        try {
            int custId = Integer.parseInt(args[0]);
            uit.refreshCustomerRecommendations(custId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    } //main

}
