/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package oracle.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Activity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Activity\",\"namespace\":\"oracle.avro\",\"fields\":[{\"name\":\"custId\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"movieId\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"activity\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"genreId\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"recommended\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"time\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"rating\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"price\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"position\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Integer custid;
  @Deprecated public java.lang.Integer movieid;
  @Deprecated public java.lang.Integer activity;
  @Deprecated public java.lang.Integer genreid;
  @Deprecated public java.lang.CharSequence recommended;
  @Deprecated public java.lang.CharSequence time;
  @Deprecated public java.lang.Integer rating;
  @Deprecated public java.lang.Double price;
  @Deprecated public java.lang.Integer position;

  /**
   * Default constructor.
   */
  public Activity() {}

  /**
   * All-args constructor.
   */
  public Activity(java.lang.Integer custid, java.lang.Integer movieid, java.lang.Integer activity, java.lang.Integer genreid, java.lang.CharSequence recommended, java.lang.CharSequence time, java.lang.Integer rating, java.lang.Double price, java.lang.Integer position) {
    this.custid = custid;
    this.movieid = movieid;
    this.activity = activity;
    this.genreid = genreid;
    this.recommended = recommended;
    this.time = time;
    this.rating = rating;
    this.price = price;
    this.position = position;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return custid;
    case 1: return movieid;
    case 2: return activity;
    case 3: return genreid;
    case 4: return recommended;
    case 5: return time;
    case 6: return rating;
    case 7: return price;
    case 8: return position;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: custid = (java.lang.Integer)value$; break;
    case 1: movieid = (java.lang.Integer)value$; break;
    case 2: activity = (java.lang.Integer)value$; break;
    case 3: genreid = (java.lang.Integer)value$; break;
    case 4: recommended = (java.lang.CharSequence)value$; break;
    case 5: time = (java.lang.CharSequence)value$; break;
    case 6: rating = (java.lang.Integer)value$; break;
    case 7: price = (java.lang.Double)value$; break;
    case 8: position = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'custid' field.
   */
  public java.lang.Integer getCustid() {
    return custid;
  }

  /**
   * Sets the value of the 'custid' field.
   * @param value the value to set.
   */
  public void setCustid(java.lang.Integer value) {
    this.custid = value;
  }

  /**
   * Gets the value of the 'movieid' field.
   */
  public java.lang.Integer getMovieid() {
    return movieid;
  }

  /**
   * Sets the value of the 'movieid' field.
   * @param value the value to set.
   */
  public void setMovieid(java.lang.Integer value) {
    this.movieid = value;
  }

  /**
   * Gets the value of the 'activity' field.
   */
  public java.lang.Integer getActivity() {
    return activity;
  }

  /**
   * Sets the value of the 'activity' field.
   * @param value the value to set.
   */
  public void setActivity(java.lang.Integer value) {
    this.activity = value;
  }

  /**
   * Gets the value of the 'genreid' field.
   */
  public java.lang.Integer getGenreid() {
    return genreid;
  }

  /**
   * Sets the value of the 'genreid' field.
   * @param value the value to set.
   */
  public void setGenreid(java.lang.Integer value) {
    this.genreid = value;
  }

  /**
   * Gets the value of the 'recommended' field.
   */
  public java.lang.CharSequence getRecommended() {
    return recommended;
  }

  /**
   * Sets the value of the 'recommended' field.
   * @param value the value to set.
   */
  public void setRecommended(java.lang.CharSequence value) {
    this.recommended = value;
  }

  /**
   * Gets the value of the 'time' field.
   */
  public java.lang.CharSequence getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.CharSequence value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'rating' field.
   */
  public java.lang.Integer getRating() {
    return rating;
  }

  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(java.lang.Integer value) {
    this.rating = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'position' field.
   */
  public java.lang.Integer getPosition() {
    return position;
  }

  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(java.lang.Integer value) {
    this.position = value;
  }

  /** Creates a new Activity RecordBuilder */
  public static oracle.avro.Activity.Builder newBuilder() {
    return new oracle.avro.Activity.Builder();
  }
  
  /** Creates a new Activity RecordBuilder by copying an existing Builder */
  public static oracle.avro.Activity.Builder newBuilder(oracle.avro.Activity.Builder other) {
    return new oracle.avro.Activity.Builder(other);
  }
  
  /** Creates a new Activity RecordBuilder by copying an existing Activity instance */
  public static oracle.avro.Activity.Builder newBuilder(oracle.avro.Activity other) {
    return new oracle.avro.Activity.Builder(other);
  }
  
  /**
   * RecordBuilder for Activity instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Activity>
    implements org.apache.avro.data.RecordBuilder<Activity> {

    private java.lang.Integer custid;
    private java.lang.Integer movieid;
    private java.lang.Integer activity;
    private java.lang.Integer genreid;
    private java.lang.CharSequence recommended;
    private java.lang.CharSequence time;
    private java.lang.Integer rating;
    private java.lang.Double price;
    private java.lang.Integer position;

    /** Creates a new Builder */
    private Builder() {
      super(oracle.avro.Activity.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(oracle.avro.Activity.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Activity instance */
    private Builder(oracle.avro.Activity other) {
            super(oracle.avro.Activity.SCHEMA$);
      if (isValidValue(fields()[0], other.custid)) {
        this.custid = data().deepCopy(fields()[0].schema(), other.custid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.movieid)) {
        this.movieid = data().deepCopy(fields()[1].schema(), other.movieid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.activity)) {
        this.activity = data().deepCopy(fields()[2].schema(), other.activity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.genreid)) {
        this.genreid = data().deepCopy(fields()[3].schema(), other.genreid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.recommended)) {
        this.recommended = data().deepCopy(fields()[4].schema(), other.recommended);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.time)) {
        this.time = data().deepCopy(fields()[5].schema(), other.time);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.rating)) {
        this.rating = data().deepCopy(fields()[6].schema(), other.rating);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.price)) {
        this.price = data().deepCopy(fields()[7].schema(), other.price);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.position)) {
        this.position = data().deepCopy(fields()[8].schema(), other.position);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'custid' field */
    public java.lang.Integer getCustid() {
      return custid;
    }
    
    /** Sets the value of the 'custid' field */
    public oracle.avro.Activity.Builder setCustid(java.lang.Integer value) {
      validate(fields()[0], value);
      this.custid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'custid' field has been set */
    public boolean hasCustid() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'custid' field */
    public oracle.avro.Activity.Builder clearCustid() {
      custid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'movieid' field */
    public java.lang.Integer getMovieid() {
      return movieid;
    }
    
    /** Sets the value of the 'movieid' field */
    public oracle.avro.Activity.Builder setMovieid(java.lang.Integer value) {
      validate(fields()[1], value);
      this.movieid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'movieid' field has been set */
    public boolean hasMovieid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'movieid' field */
    public oracle.avro.Activity.Builder clearMovieid() {
      movieid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'activity' field */
    public java.lang.Integer getActivity() {
      return activity;
    }
    
    /** Sets the value of the 'activity' field */
    public oracle.avro.Activity.Builder setActivity(java.lang.Integer value) {
      validate(fields()[2], value);
      this.activity = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'activity' field has been set */
    public boolean hasActivity() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'activity' field */
    public oracle.avro.Activity.Builder clearActivity() {
      activity = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'genreid' field */
    public java.lang.Integer getGenreid() {
      return genreid;
    }
    
    /** Sets the value of the 'genreid' field */
    public oracle.avro.Activity.Builder setGenreid(java.lang.Integer value) {
      validate(fields()[3], value);
      this.genreid = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'genreid' field has been set */
    public boolean hasGenreid() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'genreid' field */
    public oracle.avro.Activity.Builder clearGenreid() {
      genreid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'recommended' field */
    public java.lang.CharSequence getRecommended() {
      return recommended;
    }
    
    /** Sets the value of the 'recommended' field */
    public oracle.avro.Activity.Builder setRecommended(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.recommended = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'recommended' field has been set */
    public boolean hasRecommended() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'recommended' field */
    public oracle.avro.Activity.Builder clearRecommended() {
      recommended = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'time' field */
    public java.lang.CharSequence getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public oracle.avro.Activity.Builder setTime(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.time = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'time' field */
    public oracle.avro.Activity.Builder clearTime() {
      time = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'rating' field */
    public java.lang.Integer getRating() {
      return rating;
    }
    
    /** Sets the value of the 'rating' field */
    public oracle.avro.Activity.Builder setRating(java.lang.Integer value) {
      validate(fields()[6], value);
      this.rating = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'rating' field has been set */
    public boolean hasRating() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'rating' field */
    public oracle.avro.Activity.Builder clearRating() {
      rating = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.Double getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public oracle.avro.Activity.Builder setPrice(java.lang.Double value) {
      validate(fields()[7], value);
      this.price = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'price' field */
    public oracle.avro.Activity.Builder clearPrice() {
      price = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'position' field */
    public java.lang.Integer getPosition() {
      return position;
    }
    
    /** Sets the value of the 'position' field */
    public oracle.avro.Activity.Builder setPosition(java.lang.Integer value) {
      validate(fields()[8], value);
      this.position = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'position' field has been set */
    public boolean hasPosition() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'position' field */
    public oracle.avro.Activity.Builder clearPosition() {
      position = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public Activity build() {
      try {
        Activity record = new Activity();
        record.custid = fieldSetFlags()[0] ? this.custid : (java.lang.Integer) defaultValue(fields()[0]);
        record.movieid = fieldSetFlags()[1] ? this.movieid : (java.lang.Integer) defaultValue(fields()[1]);
        record.activity = fieldSetFlags()[2] ? this.activity : (java.lang.Integer) defaultValue(fields()[2]);
        record.genreid = fieldSetFlags()[3] ? this.genreid : (java.lang.Integer) defaultValue(fields()[3]);
        record.recommended = fieldSetFlags()[4] ? this.recommended : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.time = fieldSetFlags()[5] ? this.time : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.rating = fieldSetFlags()[6] ? this.rating : (java.lang.Integer) defaultValue(fields()[6]);
        record.price = fieldSetFlags()[7] ? this.price : (java.lang.Double) defaultValue(fields()[7]);
        record.position = fieldSetFlags()[8] ? this.position : (java.lang.Integer) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
